FROM node:18-slim

WORKDIR /app

COPY backend/package.json backend/package-lock.json ./

RUN npm ci

COPY backend/ .
COPY shared-types/ ./shared-types/

EXPOSE 5000

CMD ["sh", "-c", "if [ \"$NODE_ENV\" = \"production\" ]; then npm run build && npm run start; else npm run dev; fi"]
