FROM node:18-slim

WORKDIR /app

COPY backend/package.json backend/package-lock.json ./

RUN npm ci

COPY backend/ .
COPY shared-types/ ./shared-types/

EXPOSE 5000

RUN npm run build

CMD ["npm", "run", "start"]
