FROM node:18-slim

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./

RUN npm ci

COPY frontend/ .
COPY shared-types/ ./shared-types/

ENV NODE_ENV=production
ENV NEXT_PUBLIC_API_URL=/backend-api

EXPOSE 3000

RUN npm run build

CMD ["npm", "run", "start"]
