services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    restart: always

  frontend:
    environment:
      NODE_ENV: production
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  backend:
    environment:
      NODE_ENV: production
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  db:
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  pgadmin:
    deploy:
      replicas: 0
