services:
  frontend:
    build: ./frontend
    container_name: woolies-watcher-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
      - ./shared-types:/app/shared-types
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: /backend-api
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    container_name: woolies-watcher-backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app:delegated
      - backend_node_modules:/app/node_modules
      - ./shared-types:/app/shared-types
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:14
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  migrations:
    image: postgres:14
    container_name: postgres_migrations
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db
    volumes:
      - ./db/migrations:/migrations
    entrypoint: ['sh', '-c', './migrations/migrate.sh']

  redis:
    image: redis:6
    container_name: redis_service
    ports:
      - '6379:6379'
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
  frontend_node_modules:
  backend_node_modules:
