version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: woolies-watcher-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - ./types:/app/types
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: woolies-watcher-backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
      - ./types:/app/types
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/woolies-watcher
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: woolies-watcher
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  migrations:
    image: postgres:14
    container_name: postgres_migrations
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: woolies-watcher
    depends_on:
      - db
    volumes:
      - ./db/migrations:/migrations
    entrypoint: ['sh', '-c', './migrations/migrate.sh']

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  postgres_data:
