services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    restart: always

  frontend:
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: /backend-api # Relative path
    expose:
      - '3000' # Internal port for Nginx

  backend:
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    expose:
      - '5000' # Internal port for Nginx
