name: Deploy GHCR Images

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and Publish Images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ww-frontend:latest

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ww-backend:latest
